name: Azure pipeline

on:
  push:
    branches:
    - main
  workflow_dispatch:

env:
  TERRAFORM_VERSION: "1.13.3"
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:

  tf-run:
    name: Terraform on Azure
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:

    - name: Step 01 - Terraform Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Step 02 - CheckOut GitHub Repo
      uses: actions/checkout@v4

    - name: Step 03 - Terraform Init
      run: terraform -chdir=./terraform init -input=false

    - name: Step 04 - Terraform Validate
      run: terraform -chdir=./terraform validate

    - name: Step 05 - Terraform Plan
      run: terraform -chdir=./terraform plan -out tfplan

    - name: Step 06 - Terraform Apply
      run: terraform -chdir=./terraform apply tfplan

    - name: Step 07 - Terraform Show
      run: terraform -chdir=./terraform show